name: ml
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pip
  - pip:
    - mlflow==2.9.0
    - optuna==3.4.0
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - albumentations==1.3.1
    - timm==0.9.10
    - opencv-python==4.8.1.78
    - psutil==5.9.6
    - seaborn==0.13.0
    - tqdm==4.66.4
    - wandb==0.16.1
    - imblearn
